[wallet credential]
private_key = "2T2mRwY4fE7AJuCWj9TpUYYPEDaRsmPf4qKqNHGHMQSmSeMPZqTpZiS7vwU98qjHCUPMVTpmm61LArw72h7R6XHo"

[relayer credential]
confirm_service = "JITO" # JITO / ZERO_SLOT / NOZOMI
jito_api_key = "751f7390-2f50-11f0-858a-6bee29fce9c1"
nozomi_api_key = "4516a74a-ad06-4faf-9de4-10cce6e37f6b"
zero_slot_key = "8d24b393b8c942c2b5e4bce55efc44a6"

[gRPC credential]
rpc_endpoint = "http://quadratically-encounter-mkptthwaoy-dedicated-bypass.helius-rpc.com?api-key=79e0a224-045e-4e54-ab47-e184bb2446ef"
grpc_endpoint = "http://adjures-skylighted-pntxljtudq-dedicated-bypass.helius-rpc.com:2052"
grpc_token = "9d068e25-131c-4bbd-aa8d-cb541ef78de5"

[buy_setting]
buy_amount_sol = 0.0001

[slippage]
slippage = 50